name: Deploy Projects to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build and deploy Project 1
      - name: Build Project 1
        run: |
          cd project1
          npm install && npm run build  # Adjust for your framework
          
      - name: Deploy Project 1
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: project1/dist       # Adjust if your build folder differs
          destination_dir: project1       # Deploys to /project1 subpath

      # Repeat for Project 2
      - name: Build Project 2
        run: |
          cd project2
          npm install && npm run build
          
      - name: Deploy Project 2
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: project2/public    # Adjust as needed
          destination_dir: project2       # Deploys to /project2 subpath
