name: Deploy React Portfolio
on:
  push:
    branches: [ main ]
    paths: [ 'portfolio/**' ]  # Only run when /portfolio changes
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd portfolio && npm install && npm run deploy
